# Generated by Django 6.0.6 on 2026-06-21 11:48

import apps.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_primary', models.CharField(default='+919075075993', max_length=20)),
                ('whatsapp_number', models.CharField(default='919075075993', help_text='Digits only, no + prefix (used for wa.me links).', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('business_address', models.TextField(blank=True)),
                ('city', models.CharField(default='Byndoor', max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('delivery_areas', models.TextField(blank=True, help_text='One delivery area per line (e.g. Byndoor, Gangolli, Kundapur).')),
                ('business_hours', models.TextField(blank=True, help_text='One line per entry, e.g. Mon–Sat: 9 AM – 7 PM')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
            bases=(apps.core.mixins.SingletonModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_location', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')])),
                ('review_text', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Review',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Super Tasty Cakes Studio', max_length=100)),
                ('hero_headline', models.CharField(default='Handcrafted Cakes for Every Celebration', max_length=200)),
                ('hero_subheadline', models.TextField(blank=True, default='Fresh, beautiful cakes delivered across Byndoor, Gangolli, Kundapur & nearby areas.')),
                ('business_tagline', models.CharField(blank=True, max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_text', models.TextField(blank=True)),
                ('established_year', models.PositiveIntegerField(default=2021)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('instagram_url', models.URLField(blank=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('google_maps_embed', models.TextField(blank=True, help_text='Paste the full Google Maps iframe embed code.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
            bases=(apps.core.mixins.SingletonModelMixin, models.Model),
        ),
    ]
