# Generated by Django 6.0.6 on 2026-06-21 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='cakes/')),
                ('price_half_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_one_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_per_piece', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_display_note', models.CharField(blank=True, help_text='Optional override, e.g. "₹35 / ₹70"', max_length=100)),
                ('has_egg_option', models.BooleanField(default=True)),
                ('has_eggless_option', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cakes', to='cakes.category')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
