# Generated by Django 6.0.6 on 2026-06-22 08:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_alter_cake_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
