# Generated by Django 6.0.6 on 2026-06-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('occasion', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('wedding', 'Wedding'), ('engagement', 'Engagement'), ('other', 'Other')], max_length=20)),
                ('flavor', models.CharField(max_length=100)),
                ('weight', models.CharField(choices=[('0.5kg', '0.5 kg'), ('1kg', '1 kg'), ('1.5kg', '1.5 kg'), ('2kg', '2 kg'), ('custom', 'Custom')], max_length=20)),
                ('delivery_date', models.DateField()),
                ('design_description', models.TextField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='custom_orders/')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Private notes — not shown to customers.')),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Cake Request',
                'ordering': ['-created_at'],
            },
        ),
    ]
